export const RESPONSE_MESSAGE = {
  USER_REGISTERED: 'User registered successfully',
  USER_ALREADY_EXISTS: 'User already exists!',
  USER_NOT_FOUND: 'User not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_LOGGED_IN: 'User logged in successfully',
  USER_LOGGED_OUT: 'User logged out successfully',
  USER_UPDATED: 'User updated successfully',
  USER_DELETED: 'User deleted successfully',
  DELETE_USER_FAILED: 'Delete failed: User not found',
  USER_RETRIEVED: 'User details retrieved successfully',
  USER_LIST_RETRIEVED: 'Users list retrieved successfully',
  INVALID_TOKEN: 'Invalid token',
  UNAUTHORIZED: 'Unauthorized',
  TOKEN_EXPIRED: 'Token expired',
  AUTHENTICATION_FAILED: 'Authentication failed',
  PASSWORD_OR_OTP_REQUIRED: 'Either password or OTP must be provided',
  PASSWORD_OTP_REQUIRED: 'Only one of password or OTP should be provided',
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
  INVALID_EMAIL: 'Email must be a valid email address',
  REQUIRED_EMAIL: 'Email is required',
  PASSWORD_REGEX:
    'Password must include uppercase letters, lowercase letters, numbers, and symbols',
  PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
  INVALID_GENDER: 'Gender must be male, female, or other',
  PROFILE_PIC_INVALID_URL: 'Profile picture must be a valid URL',
  INVALID_CONNECTION_STATUS: 'Provided connection status is not a valid status',
  INVALID_URL: 'Invalid URL',
  CONNECTION_REQUESTS_EXIST: 'Connection request already exists',
  CONNECTION_REQUEST_SENT: 'Interest sent successfully',
  SELF_CONNECTION_REQUEST: 'Cannot send connection request to yourself',
  SELF_CONNECTION_REVIEW: 'Cannot review connection request from yourself',
  CONNECTION_REQUEST_UPDATED: 'Connection request updated successfully',
  CONNECTION_REQUEST_ALREADY_REVIEWED: 'Connection request already reviewed',
  CONNECTION_REQUESTS_DOES_NOT_EXIST: 'Connection request does not exist',
  CONNECTION_REQUESTS_REVIEWED: 'Connection requests reviewed successfully',
  INVALID_PAGE: 'Invalid page number',
  INVALID_LIMIT: 'Invalid limit number',
};
