export const RESPONSE_MESSAGE = {
  USER_REGISTERED: 'User registered successfully',
  USER_ALREADY_EXISTS: 'User already exists!',
  USER_NOT_FOUND: 'User not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_LOGGED_IN: 'User logged in successfully',
  USER_LOGGED_OUT: 'User logged out successfully',
  USER_UPDATED: 'User updated successfully',
  USER_DELETED: 'User deleted successfully',
  DELETE_USER_FAILED: 'Delete failed: User not found',
  USER_RETRIEVED: 'User details retrieved successfully',
  USER_LIST_RETRIEVED: 'Users list retrieved successfully',
  INVALID_TOKEN: 'Invalid token',
  UNAUTHORIZED: 'Unauthorized',
  TOKEN_EXPIRED: 'Token expired',
  AUTHENTICATION_FAILED: 'Authentication failed',
  PASSWORD_OR_OTP_REQUIRED: 'Either password or OTP must be provided',
  PASSWORD_OTP_REQUIRED: 'Only one of password or OTP should be provided',
  usernameTaken: (username: string) =>
    `Username ${username} is already taken. Please provide another username`,
  SOMETHING_WENT_WRONG: 'Something went wrong. Please try again later.',
  INVALID_EMAIL: 'Email must be a valid email address',
  PASSWORD_REGEX:
    'Password must include uppercase letters, lowercase letters, numbers, and symbols',
  PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long',
  INVALID_GENDER: 'Gender must be male, female, or other',
  PROFILE_PIC_INVALID_URL: 'Profile picture must be a valid URL',
};
